### ISSUE TITLE
Long titles overflow container at mobile widths

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-law-pro#3]
Visible at /attorneys/william-sanford/ in iPhone 6/7/8 emulator in Chrome:

<img width="433" alt="william_sanford" src="https://user-images.githubusercontent.com/647669/46746260-ffa24300-ccae-11e8-8230-23251688f6da.png">

Not necessarily saying this needs a fix, but wanted to flag it. We find it can cause issues for languages such as German where average word length is higher.

We have this in Genesis Sample for that reason:

```CSS
.site-container {	
	word-wrap: break-word;
}
```

**Comment by JiveDig** [comment]
Ahh, I went back and forth with this a few times actually. I eventually decided to leave it out because it caused weirdness on titles in widgets (sidebar/footer/etc) on desktop. I think it may make sense to have this on mobile sizes though, and probably only on headings/entry-titles.

I also prefer `hyphens: auto;` which looks a little better as long as the text is not an actual URL, then it adds a visual hyphen to the url. Not fun. 

I will test adding word-wrap or hyphens at our smallest breakpoint (544px)

**Comment by JiveDig** [comment]
When with word-wrap as a fallback, and hyphens auto... only on headings/titles below 544px:
```
@media only screen and (max-width: 544px) {

	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	.heading,
	.banner-title,
	.entry-title {
		word-wrap: break-word;
		-webkit-hyphens: auto;
		-ms-hyphens: auto;
		hyphens: auto;
	}

}
```
This is coming in the minor update to Mai Theme Engine.
